In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/nlpswahili/SampleSubmission.csv
/kaggle/input/nlpswahili/Train.csv
/kaggle/input/nlpswahili/VariableDefinitions.csv
/kaggle/input/nlpswahili/Test.csv


In [2]:
from fastai.text.all import *
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../input/nlpswahili/Train.csv")
df.head()

id  \
0     SW0   
1     SW1   
2    SW10   
3   SW100   
4  SW1000   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   content  \
0   SERIKALI imesema haitakuwa tayari kuona amani na utulivu wa nchi inachezewa huku ikisisitiza uwepo wa umoja kati ya wananchi bila kujali tofauti ya imani, kabila au itikadi yoyote.Hayo yalisemwa na Naibu Waziri wa Mambo ya Ndani ya Nchi, Hamad Yussuf Masauni wakati akifungua semina ya siku mbili iliyofanyika jijini Dar es Salaam ikiwahusisha viongozi wa taasisi za Kiislamu, lengo ikiwa ni kuwakumbusha kuhubiri amani katika sehemu zao.Naibu Waziri amesema mwelekeo na malengo ya Serikali ya Awamu ya Tano ni kukuza maendeleo katika sehemu mbalimbali nchini lengo ikiwa kuinua maisha ya wananc...   
1   Mkuu wa Mkoa wa Tabora, Aggrey Mwanri amesitisha likizo za viongozi wote mkoani humo kutekeleza maazimio ya Jukwaa la Fursa za Biashara la mkoa huo.Mwanri ameagiza kuwa, hata kama kuna likizo zimeidhinishwa zifutwe.Amemuagiza Katibu Tawala wa Mkoa huo, Msalika Makungu kuandika barua kwa viongozi kuhusu uamuzi huo na amebainisha kuwa hakushauriwa na mtu, kaamua yeye.“Anayebisha anyooshe mkono, ajifanye angalau anajikuna tu” amesema Mwanri kwenye jukwaa hilo la nane lililomalizika leo.Amewaeleza viongozi wa Tabora kuwa, mambo waliyopanga kuyafanya wakati wa likizo nje ya Tabora wanaweza kuy...   
2   SERIKALI imetoa miezi sita kwa taasisi zote za umma ambazo hazitumii mfumo wa GePG katika ukusanyaji wa fedha kufanya hivyo na baada ya hapo itafanya ukaguzi na kuwawajibisha maofi sa masuhuli walioshindwa kutekeleza hilo.Akifungua mkutano wa mwaka wa kwanza wa watumiaji wa mfumo huo jana jijini hapa, Naibu Katibu Mkuu Wizara ya Fedha na Mipango, Dk Hartibu Kazungu alisema ukaguzi huo ambao utaanza kufanyika Juni mwakani baada ya kipindi kilichowekwa kupita ili kuwabaini maofisa wazembe.Alisema, wizara yake itafanya ukaguzi wa ofisi zote za umma ili kubaini kama kuna fedha zinazokusanywa ...   
3   KAMPUNI ya mchezo wa kubahatisha ya M-bet imeingia makubaliano ya udhamini na timu ya soka ya Manispaa ya Kinondoni (KMC) kwa miaka mitano wenye thamani ya sh Bilioni 1.Akizungumzia udhamini huo jana baada ya kusaini mkataba huo, Meneja Masoko wa Mbet, Allen Mushi alisema sababu ya kuiunga mkono timu hiyo ni baada ya kuvutiwa na kiwango bora walichokionesha timu hiyo tangu msimu uliopita. Alisema kitendo cha kumaliza ligi katika nafasi ya nne bora sio cha mchezo na kwamba hata wanapokuwa uwanjani hucheza soka la kuvutia tofauti na wengine.“Tumeichagua KMC kwasababu tumevutiwa na mambo men...   
4   WATANZANIA wamekumbushwa kusherehekea sikukuu ya Krismasi kwa kuenzi amani, umoja na kulinda tamaduni za nchi ili kupambana na changamoto mbalimbali zinazojitokeza, ikiwemo vitendo vya ushoga na matumizi ya dawa za kulevya.Akizungumza wakati wa kutoa heri ya sikukuu hiyo ya Kuzaliwa Yesu Kristo, Kiongozi wa Waislamu wa madhehebu ya Shia Ithnasheriya, Shehe Hemed Jalala alisema kuzaliwa kwa Yesu kunalenga kuhubiri na kutangaza amani ulimwenguni. Shehe Jalala alisema licha ya Wayahudi kutilia shaka kuzaliwa kwa Yesu, lakini pindi alipozaliwa alitangaza amani kwake na duniani kote akitaka ki...   

   category  
0   Kitaifa  
1  Biashara  
2   Kitaifa  
3   michezo  
4   Kitaifa

In [4]:
df['category'].unique()

array(['Kitaifa', 'Biashara', 'michezo', 'Kimataifa', 'Burudani'],
      dtype=object)

In [5]:
test = pd.read_csv('../input/nlpswahili/Test.csv')
test.head()

swahili_id  \
0  001dd47ac202d9db6624a5ff734a5e7dddafeaf2   
1  0043d97f7690e9bc02f0ed8bb2b260d1d44bad92   
2  00579c2307b5c11003d21c40c3ecff5e922c3fd8   
3  00868eeee349e286303706ef0ffd851f39708d37   
4  00a5cb12d3058dcf2e42f277eee599992db32412   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   content  
0   MKUU wa Wilaya ya Bahi, Mkoani Dodoma, Mwanahamisi Munkunda ameuagiza uongozi wa halmashauri ya wilaya hiyo na kamati zote za usimaminzi wa ujenzi wa mradi wa hospitali yao kukamilisha ujenzi Mei 30, mwaka huu.Alitoa agizo hilo mwishoni mwa wiki Wakati akizindua eneo itakapokengwa hospitali hiyo. Alisema kutokana na maandalizi yote ya msingi ikiwemo ununuzi wa vifaa vya ujenzi (bati, nondo,mchanga) kukamilika, hakuna sababu inayoweza kukwamisha ujenzi huo. “ Nataka mradi huu kukamilika Mei 30, mwaka huu, kutokana na vifaa vyote kukamilika. Tuwe tumekamilisha majengo yote saba,” alisema.Al...  
1   MWISHONI mwa wiki hii, Timu ya Soka ya Taifa, Taifa Stars itakuwa na kibarua kizito dhidi ya Sudan, katika mechi ya kuwania kufuzu Fainali za Michuano ya Afrika kwa wachezaji wa ndani, Chan.Katika harakati za kujiandaa na mechi hiyo, Stars juzi ilicheza mechi ya kirafiki na Rwanda mjini Kigali na kutoka suluhu. Matokeo hayo yanaonekana kumridhisha kocha wa timu hiyo, Etienne Ndayiragije na kusema amepata kipimo sahihi kabla ya kucheza na Sudan mechi ambayo Stars inahitaji ushindi wa kuanzia mabao mawili kusonga mbele baada ya kupoteza mechi ya nyumbani kwa bao 1-0.Ndayiragije alisema wali...  
2   THAMANI ya mauzo ya bidhaa za Afrika Mashariki katika Umoja wa Ulaya (EU) yameongezeka hadi Dola za Marekani bilioni 2.5 (Sh trilioni 5.2 za Tanzania) mwaka 2017, sawa na ongezeko la asilimia nane.Taarifa hiyo ni kwa mujibu wa Kituo cha Biashara cha Kimataifa (ITC).Kwa mujibu wa ITC, bidhaa kutoka ukanda huo zilizouzwa Ulaya kwa mwaka 2016 zilikuwa na thamani ya Dola milioni 2.3 (Sh trilioni 4.83 za Tanzania), hivyo kumekuwa na ongezeko la takribani Sh bilioni 400. Mkurugenzi wa Sekta ya Uzalishaji ya EAC, Jean Baptiste, amesema hivi karibuni jijini Arusha yalipo makao makuu ya jumuiya hi...  
3   MENEJA Mawasiliano na Utetezi wa asasi ya AGPAHI amefariki dunia gafla baada ya kuanguka akiwa katika shughuli zake za kikazi huko Kahama, Shinyanga leo. AGPAHI ni asasi ya kiraia inayojishughulisha na mapambano dhidi ya maambukizi ya Virusi vya Ukimwi na kuboresha maisha ya watoto na familia kwa ujumla. Mkurugenzi wa Shirika hilo, Sekela Mwakyusa amelithibitishia gazeti la HabariLeo, toleo la mtandaoni kuwa, mwandishi huyo wa zamani alijisikia vibaya jana, Alhamisi lakini hali yake ilirejea kawaida.Ameongeza leo asubuhi Agnes aliulizwa iwapo ataenda hospitalini kwa matibabu zaidi lakini ...  
4   WAZIRI wa Kilimo, Japhet Hasunga amesema serikali inajenga kiwanda cha kuchakata mazao ya korosho (mabibo) ili kuzalisha, kutengeneza juisi na mvinyo Naliendele Mtwara.Waziri Hasunga alitoa kauli hiyo wakati akijibu swali la nyongeza la Mbunge wa Ndanda, Cecily Mwambe (Chadema), aliyetaka kujua utafiti wa kuongeza thamani mazao ya korosho (mabibo) umefikia wapi na lini juisi na mvinyo zitaanza kutengenezwa katika Kituo cha Utafiti Kilimo cha Naliendele (NARI) Mtwara.Hasunga alisema ni kweli utafiti wa kina ulifanyika kuhusu namna ya kuongeza thamani mazao ya korosho (mabibo) ili kutengene...

In [6]:
concat = pd.concat([df,test], sort=False)

In [7]:
data_lm = TextDataLoaders.from_df(concat, text_col='content', is_lm=True, valid_pct=0.2)

/opt/conda/lib/python3.7/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [8]:
# create and train language model
learn = language_model_learner(data_lm, AWD_LSTM, metrics=[accuracy, Perplexity()], wd=0.1).to_fp16()


In [9]:
learn.fit_one_cycle(1, 1e-2)

In [10]:
learn.save('1epoch')

Path('models/1epoch.pth')

In [11]:
learn = learn.load('1epoch')

In [12]:
learn.unfreeze()
learn.fit_one_cycle(10, 1e-3)

In [13]:
learn.save_encoder('finetune')

In [14]:
# Time to train the classifier using the language model 
data_class = TextDataLoaders.from_df(df, text_col="content", label_col="category", valid_pct=0.2, text_vocab=data_lm.vocab)

/opt/conda/lib/python3.7/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [15]:
learn = text_classifier_learner(data_class, AWD_LSTM, drop_mult=0.5, metrics=accuracy)

In [16]:
learn = learn.load_encoder('finetune')

In [17]:
learn.fit_one_cycle(1, 2e-2)

In [18]:
learn.freeze_to(-2)
learn.fit_one_cycle(1, slice(1e-2/(2.6**4),1e-2))

In [19]:
learn.freeze_to(-3)
learn.fit_one_cycle(1, slice(5e-3/(2.6**4),5e-3))

In [20]:
learn.unfreeze()
learn.fit_one_cycle(2, slice(1e-3/(2.6**4),1e-3))

In [21]:
learn.save('final_model')

Path('models/final_model.pth')

In [22]:
learn.show_results(max_n=5)

In [23]:
test_dl = learn.dls.test_dl(test['content'])

In [24]:
preds, target = learn.get_preds(dl=test_dl)

In [25]:
preds = preds.numpy()
preds

array([[4.0664976e-03, 1.4693043e-03, 3.2631145e-03, 9.7949570e-01,
        1.1705377e-02],
       [9.4401703e-04, 1.6530217e-03, 2.9950698e-03, 2.2972740e-02,
        9.7143519e-01],
       [5.8824635e-01, 7.1178386e-03, 8.3269197e-03, 3.9423695e-01,
        2.0719317e-03],
       ...,
       [2.0233376e-04, 1.5692385e-03, 2.5739253e-03, 1.1406431e-02,
        9.8424810e-01],
       [1.5213006e-03, 7.2677624e-03, 7.1725352e-03, 3.6999084e-02,
        9.4703931e-01],
       [1.8580666e-02, 1.6533927e-03, 3.1586955e-03, 9.4935542e-01,
        2.7251806e-02]], dtype=float32)

In [26]:
preds = np.around(preds,decimals=0)
preds

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.]], dtype=float32)

In [27]:
preds = preds.astype(int)
preds

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0]])

In [28]:
testData = pd.read_csv('../input/nlpswahili/Test.csv', index_col='swahili_id')

In [29]:
submission =  pd.DataFrame(preds, columns = ['biashara', 'burudani', 'kimataifa', 'kitaifa', 'michezo'])
submission.index = testData.index
submission.index.rename('test_id', inplace=True)

# Rearrange columns to match submission guidelines
submission = submission[["kitaifa", "michezo", "biashara", "kimataifa", "burudani"]]
print(submission.head())

# Save to submission.csv
submission.to_csv('Submission.csv')

                                          kitaifa  michezo  biashara  \
test_id                                                                
001dd47ac202d9db6624a5ff734a5e7dddafeaf2        1        0         0   
0043d97f7690e9bc02f0ed8bb2b260d1d44bad92        0        1         0   
00579c2307b5c11003d21c40c3ecff5e922c3fd8        0        0         1   
00868eeee349e286303706ef0ffd851f39708d37        1        0         0   
00a5cb12d3058dcf2e42f277eee599992db32412        1        0         0   

                                          kimataifa  burudani  
test_id                                                        
001dd47ac202d9db6624a5ff734a5e7dddafeaf2          0         0  
0043d97f7690e9bc02f0ed8bb2b260d1d44bad92          0         0  
00579c2307b5c11003d21c40c3ecff5e922c3fd8          0         0  
00868eeee349e286303706ef0ffd851f39708d37          0         0  
00a5cb12d3058dcf2e42f277eee599992db32412          0         0  


In [30]:
submission.to_csv('Submission.csv')